### ISSUE TITLE
Rethink config.yml

### ISSUE THREAD

**Issue by ImCiryus** [CiryusMedia/ChallengesNeo#144]
The config.yml is far too bad to be effectively usable at the moment. 

Is:
```
#Challenges
RandomBlocksFull: false
RandomBlocksLoottable: false
RandomMobsLoottable: false
RandomMobsFull: false

InventorySync: false

...

#Random challenge stuff
UnsafeRandomEnchantments: true
UnsafeEnchantmentBounds: 100
UnsafeRandomPotions: true
UnsafeRandomPotionBounds: 20
RandomPotionDuration: 30 #In Minutes

...
```

Should:
```
challenge:
  random:
    blocks:
      full: false
      loottable: false
    mobs:
      full: false
      loottable: false
  sync:
    inventory: false

...

random:
  unsafe:
    enchantmenst: true
    bounds: 100
    potions: true
    potionBounds: 20
    potionDuration: 30 #In Minutes

...
```
